SELECT * FROM employees ORDER BY FIRST_NAME, LAST_NAME;

SELECT FIRST_NAME, LAST_NAME, SALARY, SALARY * 0.15 AS TAX FROM employees;

SELECT SUM(SALARY) AS SALARY_SUM FROM employees;

SELECT MIN(SALARY) AS MIN_SALARY, MAX(SALARY) AS MAX_SALARY FROM employees;

SELECT AVG(SALARY) AS AVG_SALARY, COUNT(EMPLOYEE_ID) AS NUM_OF_EMPLOYEES FROM employees